[green-monochrome-monitor]
submodule = "extensions/green-monochrome-monitor"
id = "green-monochrome-monitor"
name = "Green Monochrome Monitor CRT Phosphor"
version = "0.1.3"
schema_version = 1
authors = [
    "Takk™ Innovate Studio <say@takk.ag>",
    "David C Cavalcante <davcavalcante@proton.me>"
]
description = "Designed to replicate the classic CRT monitors, the dark version features a black background with vibrant green text, while the light version has a soft green background for contrast."
repository = "https://github.com/takk8is/green-monochrome-monitor-crt-phosphor-theme-for-zed"
