id = "amber-monochrome-monitor-crt-phosphor"
name = "Amber Monochrome Monitor CRT Phosphor"
authors = ["David C Cavalcante <davcavalcante@proton.me>", "Takk™ Innovate Studio <say@takk.ag>"]
version = "0.1.3"
schema_version = 1
description = "Designed to replicate the classic CRT monitors, this theme features a black background with vibrant amber text for the dark mode, while the light mode offers a soft amber background for contrast."
repository = "https://github.com/takk8is/amber-monochrome-monitor-crt-phosphor-theme-for-zed"
