id = "django-snippets"
name = "Django Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Ben Cressman <cressmanbenjamin@gmail.com>"]
description = "Useful Django snippets."
repository = "https://github.com/bencres/zed-django-snippets"
snippets = "./snippets/python.json"
