id = "vscode-material-theme"
name = "VSCode Material Theme"
version = "0.9.0"
schema_version = 1
authors = ["BigHolou"]
description = "Material Theme that references VSCode"
repository = "https://github.com/BigHolou/vscode-material-theme"
