name: Other Request
description: Request a non-theme, non-language extension
labels: ["needs infrastructure"]
body:
  - type: checkboxes
    attributes:
      label: Check for existing issues
      description: Check the backlog of issues to reduce the chances of creating duplicates; if an issue already exists, place a `+1` (👍) on it.
      options:
        - label: Completed
          required: true
  - type: textarea
    attributes:
      label: Misc notes
    validations:
      required: false
