id = "jellybeans-vim"
name = "Jellybeans Theme"
version = "0.0.2"
schema_version = 1
authors = [
    "Raj Kashyap <rajkash06@gmail.com>",
]
description = "Zed port of nanotech's jellybeans.vim theme 🫘"
repository = "https://github.com/rajerthat1/jellybeans.zed"
