id = "popping-and-locking-black"
name = "Popping and Locking Black"
version = "0.0.1"
schema_version = 1
authors = ["rgomids"]
description = "Popping and Locking Black Theme"
repository = "https://github.com/rgomids/popping-and-locking-black-zed-theme"
