name = "Java"
grammar = "java"
pathSuffixes = ["java"]
lineComments = ["// "]
autoCloseBefore = ";:.,=}])>` \n\t\""
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = false },
]
