id = "oolong"
name = "Oolong"
schema_version = 1
version = "0.0.2"
authors = ["José Duarte <duarte.gmj@gmail.com>"]
description = "Deep green theme for Zed"
repository = "https://github.com/jmg-duarte/oolong-zed"
