id = "lndpnr"
name = "lndpnr"
version = "0.0.1"
schema_version = 1
description = "lndpnr theme"
repository = "https://github.com/leaandropinheiro/lndpnr"
authors = ["Leandro Pinheiro Rosa"]
themes = ["themes/lndpnr.json"]
icon_themes = []
languages = []
capabilities = []

[themes]
path = "themes/lndpnr.json"

[lib]

[grammars]

[language_servers]

[context_servers]

[agent_servers]

[slash_commands]
